// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ExceptionFailures.Application.Common.Models.EFCore;
using ExceptionFailures.Application.Common.Seeds;
using ExceptionFailures.Infrastructure.EFCore.Configurations;
using Microsoft.EntityFrameworkCore;
#nullable disable

namespace ExceptionFailures.Infrastructure.EFCore;

public partial class NorthwindDbWrite : DbContext, IDbContextWrite
{
    public virtual DbSet<Supplier> Suppliers { get; set; }
    public NorthwindDbWrite(DbContextOptions<NorthwindDbWrite> options) : base(options) { }
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    
        =>  modelBuilder.ApplyConfiguration(new SupplierConfiguration());
    
}
