// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ExceptionFailures.Application.Common.Models.EFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace ExceptionFailures.Infrastructure.EFCore.Configurations
{
    public partial class SupplierConfiguration : IEntityTypeConfiguration<Supplier>
    {
        public void Configure(EntityTypeBuilder<Supplier> entity)
        {
            entity.Property(e => e.CompanyName).IsRequired();

        }
    }
}
